import { readdir, readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, basename, extname } from "node:path";

const ARTICLES_DIR = "articles";
const BLOG_DIR = "app/blog";
const MANIFEST_FILE = "posts-manifest.ts";
const HEADER = "// AUTO-GENERATED by scripts/generate-blog.mjs — DO NOT EDIT";

// ── Minimal markdown → HTML converter (no external deps) ──

function escapeHtml(text) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function inlineFormat(text) {
  let r = escapeHtml(text);
  r = r.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1" />');
  r = r.replace(/`([^`]+)`/g, "<code>$1</code>");
  r = r.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
  r = r.replace(/\*([^*]+)\*/g, "<em>$1</em>");
  r = r.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
  return r;
}

function mdToHtml(md) {
  const lines = md.split("\n");
  const blocks = [];
  let i = 0;

  while (i < lines.length) {
    const trimmed = lines[i].trim();

    if (trimmed === "") {
      i++;
      continue;
    }

    // Fenced code block
    if (trimmed.startsWith("```")) {
      let code = "";
      i++;
      while (i < lines.length && !lines[i].trim().startsWith("```")) {
        code += lines[i] + "\n";
        i++;
      }
      i++;
      blocks.push(
        "<pre><code>" + escapeHtml(code.replace(/\n$/, "")) + "</code></pre>"
      );
      continue;
    }

    // Heading
    const h = trimmed.match(/^(#{1,6})\s+(.*)$/);
    if (h) {
      const level = h[1].length;
      blocks.push("<h" + level + ">" + inlineFormat(h[2]) + "</h" + level + ">");
      i++;
      continue;
    }

    // Horizontal rule
    if (/^(-{3,}|\*{3,}|_{3,})$/.test(trimmed)) {
      blocks.push("<hr />");
      i++;
      continue;
    }

    // Blockquote
    if (trimmed.startsWith(">")) {
      const quoteLines = [];
      while (i < lines.length && lines[i].trim().startsWith(">")) {
        quoteLines.push(lines[i].trim().replace(/^>\s?/, ""));
        i++;
      }
      blocks.push(
        "<blockquote><p>" + inlineFormat(quoteLines.join(" ")) + "</p></blockquote>"
      );
      continue;
    }

    // Unordered list
    if (/^[-*+]\s+/.test(trimmed)) {
      const items = [];
      while (i < lines.length && /^[-*+]\s+/.test(lines[i].trim())) {
        items.push(
          "<li>" +
            inlineFormat(lines[i].trim().replace(/^[-*+]\s+/, "")) +
            "</li>"
        );
        i++;
      }
      blocks.push("<ul>" + items.join("") + "</ul>");
      continue;
    }

    // Ordered list
    if (/^\d+\.\s+/.test(trimmed)) {
      const items = [];
      while (i < lines.length && /^\d+\.\s+/.test(lines[i].trim())) {
        items.push(
          "<li>" +
            inlineFormat(lines[i].trim().replace(/^\d+\.\s+/, "")) +
            "</li>"
        );
        i++;
      }
      blocks.push("<ol>" + items.join("") + "</ol>");
      continue;
    }

    // Paragraph (group consecutive plain lines)
    const paraLines = [];
    while (i < lines.length) {
      const l = lines[i].trim();
      if (l === "") break;
      if (l.startsWith("```")) break;
      if (/^#{1,6}\s+/.test(l)) break;
      if (/^[-*+]\s+/.test(l)) break;
      if (/^\d+\.\s+/.test(l)) break;
      if (l.startsWith(">")) break;
      if (/^(-{3,}|\*{3,}|_{3,})$/.test(l)) break;
      paraLines.push(l);
      i++;
    }
    blocks.push("<p>" + inlineFormat(paraLines.join(" ")) + "</p>");
  }

  return blocks.join("\n");
}

// ── Frontmatter parser (YAML-like, key: value only) ──

function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) return { data: {}, body: content };
  const data = {};
  for (const line of match[1].split("\n")) {
    const idx = line.indexOf(":");
    if (idx > -1) {
      data[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
    }
  }
  return { data, body: match[2] };
}

// ── Escaper for embedding HTML inside a TSX template literal ──

function escapeTemplate(str) {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

// ── TSX page template (array-join to avoid nested template pitfalls) ──

function pageTemplate(meta, html) {
  const escapedHtml = escapeTemplate(html);
  const titleAttr = JSON.stringify(meta.title + " | 夏蕴源");
  const descAttr = JSON.stringify(meta.description || "");
  const dateAttr = JSON.stringify(meta.date || "");

  return [
    HEADER,
    'import type { Metadata } from "next";',
    'import Link from "next/link";',
    "",
    "export const metadata: Metadata = {",
    "  title: " + titleAttr + ",",
    "  description: " + descAttr + ",",
    "};",
    "",
    "export default function BlogPostPage() {",
    "  return (",
    '    <article className="blog-content">',
    "      <Link",
    '        href="/blog"',
    '        className="mb-6 inline-block text-sm text-ink/60 transition-colors hover:text-accent"',
    "      >",
    "        \u2190 返回博客",
    "      </Link>",
    "      <time",
    '        dateTime=' + dateAttr,
    '        className="mb-6 block text-sm text-ink/60"',
    "      >",
    "        " + (meta.date || ""),
    "      </time>",
    "      <div dangerouslySetInnerHTML={{ __html: `" + escapedHtml + "` }} />",
    "    </article>",
    "  );",
    "}",
    "",
  ].join("\n");
}

// ── Manifest template ──

function manifestTemplate(posts) {
  const entries = posts
    .map(function (p) {
      return (
        "  { slug: " +
        JSON.stringify(p.slug) +
        ", title: " +
        JSON.stringify(p.title) +
        ", date: " +
        JSON.stringify(p.date) +
        ", description: " +
        JSON.stringify(p.description || "") +
        " }"
      );
    })
    .join(",\n");

  return [
    HEADER,
    "export interface BlogPostMeta {",
    "  slug: string;",
    "  title: string;",
    "  date: string;",
    "  description: string;",
    "}",
    "",
    "export const posts: BlogPostMeta[] = [",
    entries + ",",
    "];",
    "",
  ].join("\n");
}

// ── Main ──

async function main() {
  const generatedFiles = [];

  if (!existsSync(ARTICLES_DIR)) {
    await mkdir(ARTICLES_DIR, { recursive: true });
  }

  const files = (await readdir(ARTICLES_DIR)).filter(function (f) {
    return f.endsWith(".md") || f.endsWith(".markdown");
  });

  const posts = [];
  for (const file of files) {
    const filePath = join(ARTICLES_DIR, file);
    const content = await readFile(filePath, "utf-8");
    const parsed = parseFrontmatter(content);
    const data = parsed.data;
    const body = parsed.body;
    const slug = basename(file, extname(file))
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "");
    const title = data.title || basename(file, extname(file));
    const date = data.date || "";
    const description = data.description || "";
    const html = mdToHtml(body);
    posts.push({ slug: slug, title: title, date: date, description: description, html: html });
  }

  posts.sort(function (a, b) {
    return (b.date || "").localeCompare(a.date || "");
  });

  // Clean up stale generated pages
  if (existsSync(BLOG_DIR)) {
    const entries = await readdir(BLOG_DIR, { withFileTypes: true });
    const currentSlugs = new Set(posts.map(function (p) { return p.slug; }));
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const pagePath = join(BLOG_DIR, entry.name, "page.tsx");
      if (!existsSync(pagePath)) continue;
      const pageContent = await readFile(pagePath, "utf-8");
      if (!pageContent.startsWith(HEADER)) continue;
      if (!currentSlugs.has(entry.name)) {
        await rm(join(BLOG_DIR, entry.name), { recursive: true, force: true });
        console.log("  Removed stale: " + pagePath);
      }
    }
  }

  // Generate individual post pages
  for (const post of posts) {
    const postDir = join(BLOG_DIR, post.slug);
    await mkdir(postDir, { recursive: true });
    const pagePath = join(postDir, "page.tsx");
    await writeFile(pagePath, pageTemplate(post, post.html), "utf-8");
    generatedFiles.push(pagePath);
  }

  // Generate manifest
  const manifestPath = join(BLOG_DIR, MANIFEST_FILE);
  await mkdir(BLOG_DIR, { recursive: true });
  const manifestData = posts.map(function (p) {
    return { slug: p.slug, title: p.title, date: p.date, description: p.description };
  });
  await writeFile(manifestPath, manifestTemplate(manifestData), "utf-8");
  generatedFiles.push(manifestPath);

  // Output summary
  console.log("\nBlog generation complete.");
  console.log("Articles found: " + posts.length);
  console.log("Generated files:");
  for (const f of generatedFiles) {
    console.log("  " + f);
  }
}

main().catch(function (err) {
  console.error("Blog generation failed:", err);
  process.exit(1);
});
